---
title: "Meetup"
author: "Sherly Tarazona"
date: "2023-12-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Caso 1: Gran volumen de datos (>1Millón)
```{r}
#Leer

data<-read.csv("01volumen/data_ejemplo.csv", sep=";")

```


# Caso 2: Gráficos repetidos
# Objetivo: 
```{r}
#Lectura
df_resumen<-read.csv("02iterativo/df_resumen_2.csv", header=T, sep=";")
head(df_resumen,10)





```

```{r, echo=FALSE}
library(ggplot2)
library(dplyr)
library(ggpubr)
library(gridExtra)
library(grid)
library(knitr)
library(scales)
library(gtable)


# Function - table
tb_bivariate<-function(data,variable){
  
  df_tb<-data %>%
    select(tramo,splits, records_count, default_rate, summary_name,feature,num) %>%
    filter(summary_name==variable & splits!="Special") %>% 
    mutate(default_rate=as.numeric(default_rate))
  
  df_tb2<- df_tb %>% 
    mutate(TasaMalos=scales::percent(df_tb$default_rate)) %>% 
    mutate(`Categoría`=df_tb$splits) %>%
    mutate(Tramo=df_tb$tramo) %>%
    mutate(Cantidad=scales::comma(df_tb$records_count)) %>% 
    arrange(num) %>% 
    select(Tramo,`Categoría`,Cantidad,TasaMalos)
    #mutate_if(is.numeric, round, 3)
  df_tb2
  #knitr::kable(df_tb2)
}

# Function - grafico
plt_bivariate=function(data,variable, titulo){
  df<-data %>%
    select(tramo,splits, records_count, default_rate, summary_name,feature,num) %>%
    filter(summary_name==variable & splits!="Special") %>% 
    mutate(default_rate=as.numeric(default_rate))  %>% 
    mutate_if(is.numeric, round, 3)
  #color azul banco: #002060
  plt<-ggplot(df)+
    geom_bar(aes(x=reorder(tramo,num), y=records_count),
             stat="identity", fill="white", colour="#5D84CB",size = 1,width = 0.7)+
    geom_line(aes(x=reorder(tramo,num), y=default_rate*1000000),
              stat="identity", color="red",group = 4,size = 1.5)+
    theme_classic2()+
    labs(y = "%Tasa de Malos", 
         x = "Tramos",
         color = "Legend"
         #,title = paste0(" ",sep=" ",df$feature[1],collapse = NULL)
         ,title= titulo
    ) +
    theme(plot.title = element_text(hjust = 0.5,size = 14))+
    theme(text=element_text(size=12,  family="serif"),
          axis.ticks.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 9, hjust = 1),
          #axis.title.y = element_blank() 
          axis.title.y = element_text(colour = "red",size = 10 )
    )+
    scale_color_manual(values = colors)
  
  plt
}

#Unir grafico y tabla
plt_unido<-function(df_resumen,variable, tit_var,num){
  
  bivariate<-plt_bivariate(df_resumen,variable, tit_var)
  
  tt3 <- ttheme_minimal(base_size = 11,
                        colhead = list(fg_params = list(fontface=c(1,3,3))))
  
  tbl_biv<-tableGrob(tb_bivariate(df_resumen,variable),rows = NULL,theme = tt3)
  
  lint1 <- gtable_add_grob(tbl_biv,
                           grobs = segmentsGrob(
                             x0 = unit(0,"npc"),
                             y0 = unit(1,"npc"),
                             x1 = unit(1,"npc"),
                             y1 = unit(1,"npc"),
                             gp = gpar(lwd = 1)),
                           t = 1, l = 1, r = ncol(tbl_biv))
  
  lint2 <- gtable_add_grob(lint1,
                           grobs = segmentsGrob(
                             x0 = unit(0,"npc"),
                             y0 = unit(1,"npc"),
                             x1 = unit(1,"npc"),
                             y1 = unit(1,"npc"),
                             gp = gpar(lwd = 1)),
                           t = 2, l = 1, r = ncol(lint1))
  
  join<-grid.arrange(bivariate, lint2, nrow = 1)
  ggsave(paste0("plt_side",sep="_",num,".png"),join,width = 9, height= 4)
}

```

```{r}
plt_unido(df_resumen, 
          "max_cant_ent_csdirecto_1_6m", 
          "Número de entidades",
          1)
```


```{r}
plt_unido(df_resumen, 
          "edad_01m", 
          "Edad del cliente",
          1)
```

# Caso 3: Trazabilidad

```{r}
data_3<-read.csv("04formulas_extensas/data_ejemplo_formulas.csv", sep=";")
head(data_3)
table(data_3$Tipo_cliente)
```


```{r}
### Puntos de corte
vec_cortes_oro<-c(0.082,0.296,0.715,0.923)
vec_cortes_plata<-c(0.0648,0.295,0.526,0.804)
vec_cortes_bronce<-c(0.069,0.132,0.543)

tb_resumen_3<-data_3 %>% 
                 select(Probabilidad,Tipo_cliente,Monto_deuda) %>% 
                 mutate(
                 perfil_deuda=
                 ifelse(Tipo_cliente=='Oro' & Probabilidad<=vec_cortes_oro[1],"A",
                 ifelse(Tipo_cliente=='Oro' & Probabilidad<=vec_cortes_oro[2],"B",
                 ifelse(Tipo_cliente=='Oro' & Probabilidad<=vec_cortes_oro[3],"C",
                 ifelse(Tipo_cliente=='Oro' & Probabilidad<=vec_cortes_oro[4],"D",       
                 ifelse(Tipo_cliente=='Oro' & Probabilidad>vec_cortes_oro[4],"E",
              
                 ifelse(Tipo_cliente=='Plata' & Probabilidad<=vec_cortes_plata[1],"A",
                 ifelse(Tipo_cliente=='Plata' & Probabilidad<=vec_cortes_plata[2],"B",
                 ifelse(Tipo_cliente=='Plata' & Probabilidad<=vec_cortes_plata[3],"C",
                 ifelse(Tipo_cliente=='Plata' & Probabilidad<=vec_cortes_plata[4],"D",       
                 ifelse(Tipo_cliente=='Plata' & Probabilidad>vec_cortes_plata[4],"E",      
                
                 ifelse(Tipo_cliente=='Bronce' & Probabilidad<=vec_cortes_bronce[1],"A",
                 ifelse(Tipo_cliente=='Bronce' & Probabilidad<=vec_cortes_bronce[2],"B",
                 ifelse(Tipo_cliente=='Bronce' & Probabilidad<=vec_cortes_bronce[3],"C",
                 ifelse(Tipo_cliente=='Bronce' & Probabilidad>vec_cortes_bronce[3],"D","Otro"
                 ))))))))))))))) %>% 
                 group_by(Tipo_cliente) %>%
                 summarise(Prob_promedio=mean(Probabilidad)
                          ,sum_mto_deuda=sum(Monto_deuda)
                          ,conteo=n()) %>% 
                 arrange(Prob_promedio)


tb_resumen_3
```

# Caso 4: Análisis estadístico

```{r}
#Ejemplo:
german_credit <- read.table("http://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data")
colnames(german_credit) <- 
  c("chk_acct", "duration", "credit_his", "purpose", "amount", "saving_acct", "present_emp", "installment_rate", "sex", "other_debtor", "present_resid", "property", "age", "other_install", "housing", "n_credits",  "job", "n_people", "telephone", "foreign", "response")

```


```{r}
str(german_credit)
```


```{r}
test.m <- german_credit[,c(2,5,8,13,16,18,21)]
test.m$response <- as.numeric(test.m$response)
ggplot(melt(german_credit[,c(2,21)]), aes(x = variable, y = value, fill = response)) + geom_boxplot() + xlab("response") + ylab("duration")

```


# Correlacion

```{r}
grafico_correlacion<-function(variables,muestra){
  
  library(reshape2)
  library(ggplot2)
  
  cormat<-cor(as.data.frame(muestra)[,variables])
  cormat<-round(cormat,1)
  #melted_cormat <- melt(round(cormat,2))
  
  # Get lower triangle of the correlation matrix
  get_lower_tri<-function(cormat){
    cormat[upper.tri(cormat)] <- NA
    return(cormat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }
  reorder_cormat <- function(cormat){
    # Use correlation between variables as distance
    dd <- as.dist((1-cormat)/2)
    hc <- hclust(dd)
    cormat <-cormat[hc$order, hc$order]
  }
  
  # Reorder the correlation matrix
  cormat <- reorder_cormat(cormat)
  upper_tri <- get_upper_tri(cormat)
  # Melt the correlation matrix
  melted_cormat <- melt(upper_tri, na.rm = TRUE)
  # Create a ggheatmap
  ggheatmap <- 
    ggplot(melted_cormat, aes(Var2, Var1, fill = value))+
    geom_tile(color = "white")+
    scale_fill_gradient2(low = "deeppink", high = "steelblue", mid = "white", 
                         midpoint = 0, limit = c(-1,1), space = "Lab", 
                         name="Pearson/Correlation") +
    theme_minimal()+ # minimal theme
    theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                     size = 12, hjust = 1))+
    labs(title = "Correlaciones")+
    theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))+
    coord_fixed()
  # Print the heatmap
  ggheatmap + 
    geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
    
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      legend.justification = c(1, 0),
      legend.position = c(0.6, 0.7),
      legend.direction = "horizontal")+
    guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                                 title.position = "top", title.hjust = 0.5))    
}

```



```{r}

selected<-c(
 "duration"
,"n_credits"
,"amount"
,"present_resid"
,"n_people"
,"installment_rate"
 )

grafico_correlacion(variables=selected, muestra=german_credit)
```

#Regresión Logística
```{r}
german_credit$response<-as.factor(german_credit$response)
credit.glm.final <- glm(response ~ duration +  amount +  installment_rate, family = binomial, german_credit)

summary(credit.glm.final)
```

```{r}

```


