---
title: "Reporte bivariados"
author: "Sherly Tarazona"
date: "3/8/2022"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
library(readxl)
library(ggplot2)
library(dplyr)
library(ggpubr)
library(gridExtra)
library(grid)
library(knitr)
library(scales)
library(gtable)

windowsFonts()
windowsFonts(Times=windowsFont("TT Arial"))
```


```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
#Lectura
df_resumen<-read.csv("df_resumen_2.csv", header=T, sep=";")
#head(df_resumen,10)
#str(df_resumen)

```

```{r, echo=FALSE}
# Function - table
tb_bivariate<-function(data,variable){
  
  df_tb<-data %>%
    select(tramo,splits, records_count, default_rate, summary_name,feature,num) %>%
    filter(summary_name==variable & splits!="Special") %>% 
    mutate(default_rate=as.numeric(default_rate))
  
  df_tb2<- df_tb %>% 
    mutate(TasaMalos=scales::percent(df_tb$default_rate)) %>% 
    mutate(`Categoría`=df_tb$splits) %>%
    mutate(Tramo=df_tb$tramo) %>%
    mutate(Cantidad=scales::comma(df_tb$records_count)) %>% 
    arrange(num) %>% 
    select(Tramo,`Categoría`,Cantidad,TasaMalos)
    #mutate_if(is.numeric, round, 3)
  df_tb2
  #knitr::kable(df_tb2)
}

# Function - grafico
plt_bivariate=function(data,variable, titulo){
  df<-data %>%
    select(tramo,splits, records_count, default_rate, woe, summary_name,feature,num) %>%
    filter(summary_name==variable & splits!="Special") %>% 
    mutate(default_rate=as.numeric(default_rate))  %>% 
    mutate_if(is.numeric, round, 3)
  #color azul banco: #002060
  plt<-ggplot(df)+
    geom_bar(aes(x=reorder(tramo,num), y=records_count),
             stat="identity", fill="white", colour="#5D84CB",size = 1,width = 0.7)+
    geom_line(aes(x=reorder(tramo,num), y=default_rate*1000000),
              stat="identity", color="#FFC000",group = 4,size = 1.5)+
    theme_classic2()+
    labs(y = "%Tasa de Malos", 
         x = "Tramos",
         color = "Legend"
         #,title = paste0(" ",sep=" ",df$feature[1],collapse = NULL)
         ,title= titulo
    ) +
    theme(plot.title = element_text(hjust = 0.5,size = 14))+
    theme(text=element_text(size=12,  family="serif"),
          axis.ticks.y = element_blank(),
          axis.text.y = element_blank(),
          axis.text.x = element_text(size = 9, hjust = 1),
          #axis.title.y = element_blank() 
          axis.title.y = element_text(colour = "#FFC000",size = 10 )
    )+
    scale_color_manual(values = colors)
  
  plt
}

#Unir grafico y tabla
plt_unido<-function(df_resumen,variable, tit_var,num){
  
  bivariate<-plt_bivariate(df_resumen,variable, tit_var)
  
  tt3 <- ttheme_minimal(base_size = 11,
                        colhead = list(fg_params = list(fontface=c(1,3,3))))
  
  tbl_biv<-tableGrob(tb_bivariate(df_resumen,variable),rows = NULL,theme = tt3)
  
  lint1 <- gtable_add_grob(tbl_biv,
                           grobs = segmentsGrob(
                             x0 = unit(0,"npc"),
                             y0 = unit(1,"npc"),
                             x1 = unit(1,"npc"),
                             y1 = unit(1,"npc"),
                             gp = gpar(lwd = 1)),
                           t = 1, l = 1, r = ncol(tbl_biv))
  
  lint2 <- gtable_add_grob(lint1,
                           grobs = segmentsGrob(
                             x0 = unit(0,"npc"),
                             y0 = unit(1,"npc"),
                             x1 = unit(1,"npc"),
                             y1 = unit(1,"npc"),
                             gp = gpar(lwd = 1)),
                           t = 2, l = 1, r = ncol(lint1))
  
  join<-grid.arrange(bivariate, lint2, nrow = 1)
  ggsave(paste0("plt_side",sep="_",num,".png"),join,width = 9, height= 4)
}

```

### A continuación se muestran gráficos bivariados como manera de ejemplo.
### Al costado de cada gráfico se aprecia una tabla con datos

```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
plt_unido(df_resumen, 
          "max_cant_ent_csdirecto_1_6m", 
          "Número de entidades",
          1)
```

```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
plt_unido(df_resumen, 
          "edad_01m", 
          "Edad",
          1)
```

```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
plt_unido(df_resumen, 
          "antiguedad_01m", 
          "Antigüedad en el sistema financiero",
          1)
```

```{r, echo=FALSE, results='hide',message=FALSE, eval=T,warning=FALSE}
plt_unido(df_resumen, 
          "max_dias_mora_ssff_12m", 
          "Máximo días de mora Últ.12m",
          1)
```




